### PR TITLE
Varlens!

### PR DESCRIPTION
**Pull request by jdonszelmann**
Added Varlen16 and Varlen32 (and Varlen64 which is trivial) support to the serialization process

### CODE REVIEW

**Review by NULLx76 — DISMISSED** [review]
Finally!

**Review by dsluijk — DISMISSED** [review]

**Review by NULLx76 — APPROVED** [review]

**Review by dsluijk — APPROVED** [review]

**Comment by ichorid** [comment]
I wonder if you really have to implement *each* serialization element... Maybe, to simplify development, you can add them in a 'lazy' way, i.e. only do it as soon as it is needed to implement some community?

**Comment by jdonszelmann** [comment]
we're not implementing *every* one of them. we just needed varlens

**Comment by jdonszelmann** [comment]
and implementing both varlen32 and varlen16 is easy. the problem was implementing any of the two at all

**Comment by ichorid** [comment]
Good!

**Pull request merged**
